echo "Run sudo apt-get install python3-httplib2 vim python3-lxml python3-dateutil python3-mpd python3-smbus libi2c-dev python3-pigpio"
echo ""
echo "Add the following to /etc/xdg/lxsession/LXDE/autostart"
echo "@koffieui"
echo "@xset s noblank"
echo "@xset s off"
echo "@xset -dpms"
echo ""
echo "(and remove the @xscreensaver line)"
echo ""
echo "Run cp koffie_empty.db ../koffie.db"
echo "Run cp local_settings_example.py ../local_settings.py"
