echo "Run sudo apt-get install python-httplib2 vim python-lxml python-dateutil python-pysqlite2 python-mpd python-smbus libi2c-dev apach2 php5 php5-gd mpd ncmpc"
echo ""
echo "Please install pigpiod (http://abyz.co.uk/rpi/pigpio/)"
echo ""
echo "Add the following to /etc/xdg/lxsession/LXDE +="
echo "@koffieui"
echo "@xset s noblank"
echo "@xset s off"
echo "@xset -dpms"
echo ""
echo "Run cp koffie_empty.db ../koffie.db"
echo "Run cp local_settings_example.py ../local_settings.py"
