#!/bin/bash
echo "i2cdetect:";
i2cdetect -y 1
echo "test in getting the value of register 0x42:"
i2cget -y 1 0x26 0x42

echo "testing ADC read:"
i2cget -y 1 0x26 1
i2cget -y 1 0x26 1
i2cget -y 1 0x26 1

echo "testing PWM."
i2cset -y 1 0x26 0x03 0xff
sleep 1
i2cset -y 1 0x26 0x03 0xbb
sleep 1
i2cset -y 1 0x26 0x03 0x88
sleep 1
i2cset -y 1 0x26 0x03 0x00
sleep 1

